application: webapp-improved
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/.*

- url: /
  static_files: docs/index.html
  upload: docs/index.html

- url: /(.*)
  static_files: docs/\1
  upload: docs/.*
